package com.returnos.returns;

import com.returnos.auth.CurrentUser;
import com.returnos.common.ApiException;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.time.*;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1/returns") public class ReturnsController {
  private final JdbcTemplate jdbc; ReturnsController(JdbcTemplate jdbc){this.jdbc=jdbc;}
  record Line(@NotBlank String orderItemId,@Min(1) int quantity,@NotBlank String reasonCode,@Size(max=1000) String description){} record Create(@NotBlank String orderId,@NotEmpty List<@Valid Line> items,@NotNull @Pattern(regexp="REFUND|REPLACEMENT|EXCHANGE|STORE_CREDIT") String resolutionType,@Size(max=2000) String description,@NotNull @Pattern(regexp="PICKUP|DROP_OFF") String pickupKind,@Size(max=500) String pickupAddress,@Size(max=30) String pickupDate,@Size(max=60) String timeWindow){} record Cancel(@NotBlank @Size(min=3,max=500) String reason){}
  private void customer(CurrentUser u){if(u==null)throw new ApiException(HttpStatus.UNAUTHORIZED,"UNAUTHORIZED","Authentication required");if(!"CUSTOMER".equals(u.role()))throw new ApiException(HttpStatus.FORBIDDEN,"FORBIDDEN","Customer access required");}
  @PostMapping @ResponseStatus(HttpStatus.CREATED) @Transactional Map<String,Object> create(@AuthenticationPrincipal CurrentUser u,@Valid @RequestBody Create b){customer(u);var order=jdbc.query("select id,delivered_at from orders where id=? and customer_id=?",(rs,n)->{var m=new LinkedHashMap<String,Object>();m.put("id",rs.getString(1));m.put("delivered",rs.getObject(2));return m;},b.orderId(),u.id());if(order.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"ORDER_NOT_FOUND","Order not found");Object deliveredRaw=order.getFirst().get("delivered");String deliveredAt=deliveredRaw==null?null:String.valueOf(deliveredRaw);int windowDays=settingInt("RETURN_WINDOW_DAYS",30),mindDays=settingInt("CHANGED_MIND_REFUND_DAYS",14);if(deliveredAt==null||daysSince(deliveredAt)>windowDays)throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"RETURN_WINDOW_EXPIRED","This order is outside the return window");
    var orderItems=jdbc.query("select id,quantity,product_name,unit_price_paise from order_items where order_id=?",(rs,n)->{var m=new LinkedHashMap<String,Object>();m.put("id",rs.getString(1));m.put("quantity",rs.getInt(2));m.put("name",rs.getString(3));m.put("price",rs.getInt(4));return m;},b.orderId());var byId=new LinkedHashMap<String,Map<String,Object>>();for(var o:orderItems)byId.put((String)o.get("id"),o);
    var reasonCodes=new ArrayList<String>();for(var l:b.items()){var oi=byId.get(l.orderItemId());if(oi==null)throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"INVALID_ORDER_ITEM","One or more items do not belong to this order");if(jdbc.queryForObject("select count(*) from return_reasons where code=? and active=true",Integer.class,l.reasonCode())==0)throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"INVALID_REASON","Return reason is not valid: "+l.reasonCode());int claimed=jdbc.queryForObject("select coalesce(sum(ri.quantity),0) from return_items ri join returns r on r.id=ri.return_id where ri.order_item_id=? and r.status!='CANCELLED'",Integer.class,l.orderItemId());int remaining=Math.max(0,((Number)oi.get("quantity")).intValue()-claimed);if(l.quantity()>remaining)throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"QUANTITY_EXCEEDS_REMAINING","Requested quantity exceeds the remaining quantity for "+oi.get("name"));reasonCodes.add(l.reasonCode());}
    if(!allowedResolutions(reasonCodes,deliveredAt==null?Double.POSITIVE_INFINITY:daysSince(deliveredAt),mindDays).contains(b.resolutionType()))throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"RESOLUTION_NOT_ALLOWED","Resolution "+b.resolutionType()+" is not allowed for the selected reasons");
    var id=UUID.randomUUID().toString(); var number=nextReturnNumber();jdbc.update("insert into returns(id,return_number,order_id,customer_id,status,resolution_type,description) values(?,?,?,?,'REQUESTED',?,?)",id,number,b.orderId(),u.id(),b.resolutionType(),b.description());int amount=0;for(var l:b.items()){jdbc.update("insert into return_items(id,return_id,order_item_id,quantity,reason_code,description) values(?,?,?,?,?,?)",UUID.randomUUID().toString(),id,l.orderItemId(),l.quantity(),l.reasonCode(),l.description());amount+=((Number)byId.get(l.orderItemId()).get("price")).intValue()*l.quantity();}jdbc.update("insert into return_events(id,return_id,status,description) values(?,?, 'REQUESTED','Return request created by the customer')",UUID.randomUUID().toString(),id);jdbc.update("insert into pickups(id,return_id,kind,address,date,time_window,status) values(?,?,?,?,?,?,'SCHEDULED')",UUID.randomUUID().toString(),id,b.pickupKind(),b.pickupAddress(),b.pickupDate(),b.timeWindow());jdbc.update("insert into refunds(id,return_id,kind,amount_paise,status,initiated_at) values(?,?,?,?,'PENDING',now())",UUID.randomUUID().toString(),id,b.resolutionType(),amount);jdbc.update("insert into notifications(id,user_id,return_id,type,title,body) values(?,?,?, 'RETURN_CREATED','Return request received','Return '||?||' was created and is awaiting review.')",UUID.randomUUID().toString(),u.id(),id,number);return detail(u.id(),id);
  }
  @GetMapping Map<String,Object> list(@AuthenticationPrincipal CurrentUser u){customer(u);var rows=jdbc.query("select * from returns where customer_id=? order by created_at desc",(rs,n)->map(rs),u.id());var out=new ArrayList<Map<String,Object>>();for(var r:rows){var e=new LinkedHashMap<String,Object>(r);String rid=(String)r.get("id");e.put("orderNumber",jdbc.query("select order_number from orders where id=?",(rs,n)->rs.getString(1),(String)r.get("order_id")).stream().findFirst().orElse(null));var first=jdbc.query("select oi.product_name,oi.product_image_url from return_items ri join order_items oi on oi.id=ri.order_item_id where ri.return_id=? limit 1",(rs,n)->{var m=new LinkedHashMap<String,Object>();m.put("name",rs.getString(1));m.put("img",rs.getString(2));return m;},rid).stream().findFirst().orElse(null);e.put("productName",first==null?null:first.get("name"));e.put("productImageUrl",first==null?null:first.get("img"));e.put("itemQuantity",jdbc.queryForObject("select coalesce(sum(quantity),0) from return_items where return_id=?",Integer.class,rid));out.add(e);}return Map.of("returns",out);}
  @GetMapping("/{id}") Map<String,Object> get(@AuthenticationPrincipal CurrentUser u,@PathVariable String id){customer(u);return detail(u.id(),id);}
  @GetMapping("/{id}/timeline") Map<String,Object> timeline(@AuthenticationPrincipal CurrentUser u,@PathVariable String id){customer(u);detail(u.id(),id);return Map.of("events",jdbc.query("select * from return_events where return_id=? order by created_at asc",(rs,n)->map(rs),id));}
  @PostMapping("/{id}/cancel") @Transactional Map<String,Object> cancel(@AuthenticationPrincipal CurrentUser u,@PathVariable String id,@Valid @RequestBody Cancel b){customer(u);var d=detail(u.id(),id);var ret=(Map<?,?>)d.get("ret");var status=(String)ret.get("status");if(!Set.of("REQUESTED","APPROVED").contains(status))throw new ApiException(HttpStatus.CONFLICT,"CANCEL_NOT_ALLOWED","Only requested or approved returns can be cancelled");jdbc.update("update returns set status='CANCELLED',cancelled_at=now(),cancel_reason=?,updated_at=now() where id=?",b.reason(),id);jdbc.update("update pickups set status='CANCELLED',updated_at=now() where return_id=?",id);jdbc.update("update refunds set status='CANCELLED' where return_id=?",id);jdbc.update("insert into return_events(id,return_id,status,description) values(?,?, 'CANCELLED',?)",UUID.randomUUID().toString(),id,"Return cancelled by the customer: "+b.reason());jdbc.update("insert into notifications(id,user_id,return_id,type,title,body) values(?,?,?, 'RETURN_CANCELLED','Return cancelled','Return '||?||' was cancelled.')",UUID.randomUUID().toString(),u.id(),id,ret.get("return_number"));return Map.of("ret",detail(u.id(),id).get("ret"));}
  private Map<String,Object> detail(String uid,String id){var rows=jdbc.query("select * from returns where id=? and customer_id=?",(rs,n)->map(rs),id,uid);if(rows.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"RETURN_NOT_FOUND","Return not found");var out=new LinkedHashMap<String,Object>();out.put("ret",rows.getFirst());var items=jdbc.query("select ri.*,oi.product_name as \"productName\",oi.sku,oi.product_image_url as \"productImageUrl\",oi.unit_price_paise as \"unitPricePaise\" from return_items ri join order_items oi on oi.id=ri.order_item_id where ri.return_id=?",(rs,n)->map(rs),id);for(var x:items)x.put("unitPrice",((Number)x.get("unitPricePaise")).intValue()/100.0);out.put("items",items);out.put("events",jdbc.query("select * from return_events where return_id=? order by created_at asc",(rs,n)->map(rs),id));out.put("pickup",nullable("select * from pickups where return_id=?",id));out.put("refund",nullable("select * from refunds where return_id=?",id));out.put("order",nullable("select * from orders where id=?",(String)rows.getFirst().get("order_id")));return out;}
  private String nextReturnNumber(){var year=String.valueOf(Year.now(ZoneOffset.UTC).getValue());jdbc.update("insert into return_counter(year,last_seq) values(?,0) on conflict do nothing",year);int seq=jdbc.queryForObject("update return_counter set last_seq=last_seq+1 where year=? returning last_seq",Integer.class,year);return "RET-"+year+"-"+String.format("%04d",seq);}
  private int settingInt(String key,int fallback){try{var v=jdbc.query("select value::text from settings where key=?",(r,n)->r.getString(1),key);if(v.isEmpty())return fallback;return Integer.parseInt(v.getFirst().replace("\"","").trim());}catch(Exception e){return fallback;}}
  private static double daysSince(String iso){var t=parseInstant(iso);return t==null?Double.POSITIVE_INFINITY:(double)(java.time.Instant.now().toEpochMilli()-t.toEpochMilli())/86400000;}
  private static java.time.Instant parseInstant(String iso){String s=iso.trim().replace(' ','T');try{return java.time.OffsetDateTime.parse(s).toInstant();}catch(Exception a){}try{return java.time.LocalDateTime.parse(s).toInstant(java.time.ZoneOffset.UTC);}catch(Exception b){}try{return java.time.Instant.parse(s);}catch(Exception c){}return null;}
  private static List<String> allowedResolutions(List<String> codes,double daysOld,int mindDays){var all=List.of("REFUND","REPLACEMENT","EXCHANGE","STORE_CREDIT");var allowed=new ArrayList<>(all);for(var code:codes){List<String> forReason="DEFECTIVE".equals(code)||"DAMAGED".equals(code)?List.of("REFUND","REPLACEMENT","EXCHANGE"):"CHANGED_MIND".equals(code)?(daysOld<=mindDays?List.of("REFUND","STORE_CREDIT"):List.of("STORE_CREDIT")):all;allowed.removeIf(x->!forReason.contains(x));}return allowed;}
  private Map<String,Object> nullable(String sql,String arg){var x=jdbc.query(sql,(rs,n)->map(rs),arg);return x.isEmpty()?null:x.getFirst();} private static Map<String,Object> map(java.sql.ResultSet r)throws java.sql.SQLException{var x=new LinkedHashMap<String,Object>();var m=r.getMetaData();for(int i=1;i<=m.getColumnCount();i++)x.put(m.getColumnLabel(i),r.getObject(i));return x;}
}
