package com.returnos.audit;

public enum AuditAction {
    RETURN_CREATED,
    RETURN_APPROVED,
    RETURN_REJECTED,
    RETURN_SHIPPED,
    RETURN_RECEIVED,
    INSPECTION_STARTED,
    INSPECTION_COMPLETED,
    RISK_ASSESSMENT_CREATED,
    DISPOSITION_EVALUATED,
    DISPOSITION_RECOMMENDED,
    DISPOSITION_OVERRIDDEN,
    FINAL_DISPOSITION_RECORDED
}
